int64 instance_id
int64 template_id
string task_type
builtin_interfaces/Time time_from
builtin_interfaces/Time time_to
string result
uint32 page_size
int64 cursor_finished_at_sec
uint32 cursor_finished_at_nanosec
int64 cursor_instance_id
---
bool success
string failure_reason
uint32 total_count
bool has_more
TaskInstanceSummary[] instances
